language: node_js
node_js:
  - "10.13.0"

matrix:
  include:
    # Default build
  - language: c
    sudo: enabled
    env:
       - XARCH=i386

    # Esy builds
  - os: osx
    env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy
  - os: linux
    env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy

cache:
  directories:
  - $HOME/travis/.esy
  - $HOME/travis/.nvm
  - ./_build/default
  
install: ./.ci/install.sh

script: travis_wait 20 ./.ci/build.sh 
